apiVersion: v1
kind: Pod
metadata:
  name: website-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: moraruv/petstore-website
      ports:
        - containerPort: 80